💚 Avoid specs to run against Node >=24.6.0
It seems that Node 24.6.0 somehow broke the way we trigger Jest in some of our tests.

Part of our tests defined in `docs/tutorials/detect-race-conditions/snippets.spec.mjs` started to explode with the error:

> ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From queue.spec.mjs.