💚 Attempt to stabilize tests (#5989)
**Description**

<!-- Please provide a short description and potentially linked issues
justifying the need for this PR -->

Since our last bump of Vitest we experience lots of flakinesses on our
CI. Lots of runs ends with the following message:

```txt
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: [vitest-worker]: Timeout calling "onTaskUpdate"
 ❯ Object.onTimeoutError node_modules/.pnpm/vitest@3.1.4_@types+debug@4.1.12_@types+node@22.15.21_happy-dom@17.4.7_jiti@1.21.7_ligh_ed109f51547c2512f4700b2368227179/node_modules/vitest/dist/chunks/rpc.D9_013TY.js:62:10
 ❯ Timeout._onTimeout node_modules/.pnpm/vitest@3.1.4_@types+debug@4.1.12_@types+node@22.15.21_happy-dom@17.4.7_jiti@1.21.7_ligh_ed109f51547c2512f4700b2368227179/node_modules/vitest/dist/chunks/index.CJ0plNrh.js:57:62
 ❯ listOnTimeout node:internal/timers:581:17
 ❯ processTimers node:internal/timers:519:7
```

After some investigations and attempt to fix the issue I found [this
workaround](https://github.com/vitest-dev/vitest/discussions/6511#discussioncomment-13145786).
Let see if it can make it.

<!-- * Your PR is fixing a bug or regression? Check for existing issues
related to this bug and link them -->
<!-- * Your PR is adding a new feature? Make sure there is a related
issue or discussion attached to it -->

<!-- You can provide any additional context to help into understanding
what's this PR is attempting to solve: reproduction of a bug, code
snippets... -->

**Checklist** — _Don't delete this checklist and make sure you do the
following before opening the PR_

- [x] The name of my PR follows [gitmoji](https://gitmoji.dev/)
specification
- [x] My PR references one of several related issues (if any)
- [x] New features or breaking changes must come with an associated
Issue or Discussion
- [x] My PR does not add any new dependency without an associated Issue
or Discussion
- [x] My PR includes bumps details, please run `pnpm run bump` and flag
the impacts properly
- [x] My PR adds relevant tests and they would have failed without my PR
(when applicable)

<!-- More about contributing at
https://github.com/dubzzz/fast-check/blob/main/CONTRIBUTING.md -->

**Advanced**

<!-- How to fill the advanced section is detailed below! -->

- [x] Category: ✅ Add or update tests
- [x] Impacts: None

<!-- [Category] Please use one of the categories below, it will help us
into better understanding the urgency of the PR -->
<!-- * ✨ Introduce new features -->
<!-- * 📝 Add or update documentation -->
<!-- * ✅ Add or update tests -->
<!-- * 🐛 Fix a bug -->
<!-- * 🏷️ Add or update types -->
<!-- * ⚡️ Improve performance -->
<!-- * _Other(s):_ ... -->

<!-- [Impacts] Please provide a comma separated list of the potential
impacts that might be introduced by this change -->
<!-- * Generated values: Can your change impact any of the existing
generators in terms of generated values, if so which ones? when? -->
<!-- * Shrink values: Can your change impact any of the existing
generators in terms of shrink values, if so which ones? when? -->
<!-- * Performance: Can it require some typings changes on user side?
Please give more details -->
<!-- * Typings: Is there a potential performance impact? In which cases?
-->